# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='perfil',
        ),
        migrations.AddField(
            model_name='profile',
            name='info',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
