# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-15 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20161005_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='info',
            field=models.TextField(max_length=30, null=True),
        ),
    ]
