# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20161001_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
    ]
