# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-09 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
        ('blog', '0005_auto_20161005_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='type',
        ),
        migrations.AddField(
            model_name='blog',
            name='type',
            field=models.ManyToManyField(to='categorias.Category'),
        ),
    ]
