# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-20 01:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20161009_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='visibility',
            field=models.CharField(choices=[('PUB', 'Publica'), ('PRI', 'Privada')], default='PUB', max_length=3),
        ),
    ]
