# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-05 04:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20161104_0446'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image_resized',
            field=models.BooleanField(default=False),
        ),
    ]
