# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-05 04:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_blog_image_resized'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(null=True, upload_to='uploads'),
        ),
    ]
